version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: daily

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"